[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'", "rm -f main_backup.py || true"]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONIOENCODING = "utf-8"
