[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'", "rm -f main_backup.py || true", "python -m compileall middleware.py"]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONIOENCODING = "utf-8"
UVICORN_TIMEOUT_KEEP_ALIVE = "300"
UVICORN_TIMEOUT_GRACEFUL_SHUTDOWN = "30"
