[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["rm -f bun.lockb", "npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node api/index.js"

[variables]
NPM_CONFIG_PACKAGE_MANAGER = "npm"
NIXPACKS_NO_BUN = "1"
NIXPACKS_INSTALL_CMD = "npm ci"


