[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn middleware:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300 --timeout-graceful-shutdown 30"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
overlapSeconds = 30
drainingSeconds = 15
