[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont", "fontconfig", "glib", "gtk3", "libdrm", "xorg.libxcb", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libXrender", "xorg.libxshmfence", "xorg.libXi", "xorg.libXtst", "gdk-pixbuf", "cairo", "pango", "atk", "at-spi2-atk", "at-spi2-core", "cups", "dbus", "expat", "libxkbcommon", "nspr", "alsa-lib"]

[phases.install]
cmds = [
  "npm ci",
  "mkdir -p /usr/bin /app/.cache /app/.local-chromium",
  "echo 'Setting up Chromium for Railway deployment...'",
  "echo 'Downloading Puppeteer Chromium manually...'",
  "cd /app && npx puppeteer browsers install chrome",
  "echo 'Finding downloaded Chromium...'",
  "CHROMIUM_PATH=$(find /app -name chrome -type f -executable 2>/dev/null | head -1)",
  "if [ -n \"$CHROMIUM_PATH\" ]; then",
  "  echo \"Found Puppeteer Chromium at: $CHROMIUM_PATH\"",
  "  ln -sf \"$CHROMIUM_PATH\" /usr/bin/chromium",
  "  ln -sf \"$CHROMIUM_PATH\" /usr/bin/chromium-browser",
  "  ln -sf \"$CHROMIUM_PATH\" /usr/bin/google-chrome",
  "  chmod +x \"$CHROMIUM_PATH\" /usr/bin/chromium /usr/bin/chromium-browser /usr/bin/google-chrome",
  "  echo 'Testing Chromium...'",
  "  \"$CHROMIUM_PATH\" --version && echo 'Chromium is working!'",
  "else",
  "  echo 'Trying system Chromium as fallback...'",
  "  SYSTEM_CHROMIUM=$(find /nix/store -name chromium -type f -executable 2>/dev/null | head -1)",
  "  if [ -n \"$SYSTEM_CHROMIUM\" ]; then",
  "    ln -sf \"$SYSTEM_CHROMIUM\" /usr/bin/chromium",
  "    echo \"Using system Chromium: $SYSTEM_CHROMIUM\"",
  "  else",
  "    echo 'ERROR: No Chromium found'",
  "  fi",
  "fi"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_ARGS = "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu"
WA_HEADLESS = "true"
