[providers]
node = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont", "fontconfig"]

[phases.install]
cmds = [
  "npm ci",
  "mkdir -p /usr/bin /app/.cache",
  "echo 'Searching for Chromium binary...'",
  "CHROMIUM_PATH=$(find /nix/store -name chromium -type f -executable 2>/dev/null | head -1)",
  "echo \"Found Chromium at: $CHROMIUM_PATH\"",
  "if [ -n \"$CHROMIUM_PATH\" ]; then ln -sf \"$CHROMIUM_PATH\" /usr/bin/chromium && echo 'Symlink created successfully'; else echo 'ERROR: Chromium not found'; fi",
  "ls -la /usr/bin/chromium || echo 'Symlink verification failed'",
  "chmod +x /usr/bin/chromium 2>/dev/null || echo 'Could not chmod chromium'",
  "/usr/bin/chromium --version || echo 'Chromium version check failed'"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_ARGS = "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu"
WA_HEADLESS = "true"
