[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "nss", "freetype", "freetype-dev", "harfbuzz", "ca-certificates", "ttf-freefont"]

[phases.install]
cmds = [
  "npm ci",
  "mkdir -p /usr/bin",
  "find /nix/store -name chromium -type f -executable | head -1 | xargs -I {} ln -sf {} /usr/bin/chromium || true",
  "chmod +x /usr/bin/chromium || true"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
