name: Webhook AI CI

on:
  push:
    branches: [ main, master, feature/**, fix/**, ci/** ]
    paths:
      - 'webhook-ai/**'
      - '.github/workflows/webhook-ai-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'webhook-ai/**'
      - '.github/workflows/webhook-ai-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MOCK_SUPABASE: 'true'
      QUOTE_OFFLINE_FALLBACK: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'webhook-ai/package-lock.json'

      - name: Install dependencies (webhook-ai)
        run: npm ci
        working-directory: webhook-ai

      - name: Lint (webhook-ai)
        run: npm run lint
        working-directory: webhook-ai

      - name: Build (webhook-ai)
        run: npm run build
        working-directory: webhook-ai

      - name: Test (webhook-ai)
        run: npm run test -- --coverage
        working-directory: webhook-ai

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: webhook-ai-coverage
          path: webhook-ai/coverage
          if-no-files-found: ignore

